#!/bin/bash

if [ "$EUID" -eq 0 ]
  then echo "Don't run this as root."
  exit
fi

THEME_NAME="Bluefox"

WORKING_DIR="$(dirname $(readlink -f $0))"
cd $WORKING_DIR

mkdir -p ~/.local/share/icons/
cp -r icons/. ~/.local/share/icons/
cp -r cursors/. ~/.local/share/icons/
mkdir -p ~/.local/share/themes/$THEME_NAME
cp -r gtk-2.0 ~/.local/share/themes/$THEME_NAME/
cp -r gtk-3.0 ~/.local/share/themes/$THEME_NAME/
cp -r gtk-4.0 ~/.local/share/themes/$THEME_NAME/
cp -r wallpaper ~/.local/share/themes/$THEME_NAME/
cp -r index.theme ~/.local/share/themes/$THEME_NAME/
mkdir -p ~/.config/vim/colors
cp -r vim/colors/. ~/.config/vim/colors/
mkdir -p ~/.config/alacritty/themes
cp -r alacritty/themes/. ~/.config/alacritty/themes/
mkdir -p ~/.config/hypr
cp -r hyprland/. ~/.config/hypr/

FF_PROFILE_DIR=$(find ~/.mozilla/firefox/ -name "*.default-release" 2>/dev/null)

if [ -z "$FF_PROFILE_DIR" ]; then
  echo "Firefox profile not found. The theme is not installed for this app."
else
  cp -r firefox/. $FF_PROFILE_DIR
fi
